In [1]:
from iertools.tb import *
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.dates as mdates

In [2]:
# pip install git+https://github.com/AltamarMx/iertools.git

**EN LA PARTE DE ABAJO (fecha1) TIENE QUE SER UNA FECHA EN LA QUE HAYA DATOS, POR QUE SI NO MARCARÁ UN ERROR**

In [10]:
fecha1 = parse("2024-10-30")   #Año, mes , dia
fecha2 = fecha1 + pd.Timedelta("22D")

tmp= TB(config_file='config_esp.ini',device_name='est_Tlaltenango')
sensores = ["Temperatura","Humedad","Presion"]

# cafe es un nombre temporal, 
EST = pd.concat([tmp.get_df(key=sensor,start_datetime=fecha1,end_datetime=fecha2).resample('1min').mean() for sensor in sensores],axis=1)

["Temperatura","Humedad","Presion"]

C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:120: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  datos = pd.read_json(telemetry.text, orient=None)
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:128: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[key].iloc[i] = float(valor)
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:136: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  df.index += pd.Timedelta('-6H')
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:120: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  datos = pd.read_json(telemetry.text, orient=None)
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:128: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[key].iloc[i] = float(valor)
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:136: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  df.index += pd.Timedelta('-6H')
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:120: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  datos = pd.read_json(telemetry.text, orient=None)
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:128: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df[key].iloc[i] = float(valor)
C:\Users\roele\AppData\Local\Programs\Python\Python312\Lib\site-packages\iertools\tb.py:136: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  df.index += pd.Timedelta('-6H')

In [11]:
# cafe.plot()
EST

                     Temperatura    Humedad    Presion
ts
2024-10-30 09:58:00    22.288690  81.394420  677.55760
2024-10-30 09:59:00    23.032315  57.439850  880.64920
2024-10-30 10:00:00    23.101330  55.903335  880.64715
2024-10-30 10:01:00    23.149760  55.718640  880.61450
2024-10-30 10:02:00    23.244415  55.690365  880.61060
...                          ...        ...        ...
2024-11-20 10:13:00          NaN        NaN        NaN
2024-11-20 10:14:00    23.894675  67.913285  779.18830
2024-11-20 10:15:00    25.308490  53.074070  880.78250
2024-11-20 10:16:00    25.321155  52.728345  880.81050
2024-11-20 10:17:00    25.377820  56.613000  880.78720

[30260 rows x 3 columns]

In [13]:
fecha1 = parse("30/10/2024 09:58", dayfirst=True)
fecha2 = parse("30/10/2024 10:06", dayfirst=True)

# Filtra el DataFrame por rango de fechas
EST_filtrada = EST.loc[fecha1:fecha2]
EST_filtrada

                     Temperatura    Humedad    Presion
ts
2024-10-30 09:58:00    22.288690  81.394420  677.55760
2024-10-30 09:59:00    23.032315  57.439850  880.64920
2024-10-30 10:00:00    23.101330  55.903335  880.64715
2024-10-30 10:01:00    23.149760  55.718640  880.61450
2024-10-30 10:02:00    23.244415  55.690365  880.61060
2024-10-30 10:03:00    23.337800  55.736610  880.62070
2024-10-30 10:04:00    23.429610  55.274910  880.62845
2024-10-30 10:05:00    23.542310  55.152370  880.60385
2024-10-30 10:06:00    23.686985  54.976240  880.60355

In [ ]:
# import matplotlib.pyplot as plt
# import pandas as pd

# # Filtrar el rango de fechas
# start_time = '2024-09-24 22:00:00'
# end_time = '2024-09-24 22:04:00'
# filtered_data = cafe.loc[start_time:end_time]

# # Crear las subplots (3 filas, 1 columna)
# fig, axs = plt.subplots(3, 1, figsize=(10, 10), sharex=True)

# # Graficar Temperatura
# axs[0].plot(filtered_data.index, filtered_data['Temperatura'], color='red', linestyle='-', marker='o')
# # axs[0].set_title('Temperatura (°C)')
# axs[0].set_ylabel('Temperatura')

# # Graficar Humedad
# axs[1].plot(filtered_data.index, filtered_data['Humedad'], color='blue', linestyle='--', marker='s')
# # axs[1].set_title('Humedad (%)')
# axs[1].set_ylabel('Humedad')

# # Graficar Presion
# axs[2].plot(filtered_data.index, filtered_data['Presion'], color='green', linestyle='-.', marker='^')
# # axs[2].set_title('Presión (hPa)')
# axs[2].set_ylabel('Presión')

# # Configurar etiquetas comunes
# axs[2].set_xlabel('Fecha y Hora')

# # Formatear el eje X para mostrar cada minuto
# for ax in axs:
#     ax.xaxis.set_major_locator(mdates.MinuteLocator(interval=1))  # Salto de 1 minuto
#     ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M'))  # Formato de la fecha

# # Rotar las etiquetas del eje X para todas las subplots
# for ax in axs:
#     ax.tick_params(axis='x', rotation=45)

# plt.tight_layout()
# plt.show()